const complaintsData = [
  { id: 1, status: 'Pending', crime_type: 'Physical abuse', respondent_name: 'Juan Dela Cruz', created_at: 'February 1, 2024' },
  { id: 2, status: 'Resolved', crime_type: 'Child abuse', respondent_name: 'Gerard Cruz', created_at: 'February 2, 2024' },
  { id: 3, status: 'Pending', crime_type: 'Theft', respondent_name: 'Maria Santos', created_at: 'February 3, 2024' },
  { id: 4, status: 'Under Investigation', crime_type: 'Fraud', respondent_name: 'Peter Lee', created_at: 'February 4, 2024' },
  { id: 5, status: 'Resolved', crime_type: 'Burglary', respondent_name: 'Sophie Turner', created_at: 'February 5, 2024' },
  { id: 6, status: 'Under Investigation', crime_type: 'Harassment', respondent_name: 'Alex Carter', created_at: 'February 6, 2024' },
  { id: 7, status: 'Pending', crime_type: 'Identity Theft', respondent_name: 'Eva Rodriguez', created_at: 'February 7, 2024' },
  { id: 8, status: 'Resolved', crime_type: 'Domestic Violence', respondent_name: 'Daniel Smith', created_at: 'February 8, 2024' },
  { id: 9, status: 'Pending', crime_type: 'Forgery', respondent_name: 'Nina Patel', created_at: 'February 9, 2024' },
  { id: 10, status: 'Under Investigation', crime_type: 'Drug Possession', respondent_name: 'Malik Brown', created_at: 'February 10, 2024' },
  { id: 11, status: 'Pending', crime_type: 'Public Disturbance', respondent_name: 'Emily White', created_at: 'February 11, 2024' },
  { id: 12, status: 'Resolved', crime_type: 'Embezzlement', respondent_name: 'Aaron Taylor', created_at: 'February 12, 2024' },
  { id: 13, status: 'Pending', crime_type: 'Stalking', respondent_name: 'Olivia Turner', created_at: 'February 13, 2024' },
  { id: 14, status: 'Under Investigation', crime_type: 'Human Trafficking', respondent_name: 'Miguel Diaz', created_at: 'February 14, 2024' },
  { id: 15, status: 'Resolved', crime_type: 'Arson', respondent_name: 'Lily Martinez', created_at: 'February 15, 2024' },
  { id: 16, status: 'Pending', crime_type: 'Hate Crime', respondent_name: 'Lucas Anderson', created_at: 'February 16, 2024' },
  { id: 17, status: 'Under Investigation', crime_type: 'Robbery', respondent_name: 'Ava Wilson', created_at: 'February 17, 2024' },
  { id: 18, status: 'Pending', crime_type: 'Money Laundering', respondent_name: 'Caleb Foster', created_at: 'February 18, 2024' },
  { id: 19, status: 'Resolved', crime_type: 'Cyberbullying', respondent_name: 'Sofia Davis', created_at: 'February 19, 2024' },
  { id: 20, status: 'Pending', crime_type: 'Car Theft', respondent_name: 'Ethan Turner', created_at: 'February 20, 2024' },
  { id: 21, status: 'Resolved', crime_type: 'Vandalism', respondent_name: 'Sofia Reyes', created_at: 'February 21, 2024' },
  { id: 22, status: 'Under Investigation', crime_type: 'Assault', respondent_name: 'Carlos Mendoza', created_at: 'February 22, 2024' },
  { id: 23, status: 'Pending', crime_type: 'Cybercrime', respondent_name: 'Anna Garcia', created_at: 'February 23, 2024' },
  { id: 24, status: 'Under Investigation', crime_type: 'Forgery', respondent_name: 'Sophia Khan', created_at: 'February 24, 2024' },
  { id: 25, status: 'Resolved', crime_type: 'Drug Trafficking', respondent_name: 'Ryan Miller', created_at: 'February 25, 2024' },
  { id: 26, status: 'Pending', crime_type: 'Embezzlement', respondent_name: 'Lila Patel', created_at: 'February 26, 2024' },
  { id: 27, status: 'Under Investigation', crime_type: 'Burglary', respondent_name: 'Oscar Turner', created_at: 'February 27, 2024' },
  { id: 28, status: 'Pending', crime_type: 'Identity Theft', respondent_name: 'Zara Smith', created_at: 'February 28, 2024' },
  { id: 29, status: 'Resolved', crime_type: 'Child abuse', respondent_name: 'Ella Johnson', created_at: 'February 29, 2024' },
  { id: 30, status: 'Under Investigation', crime_type: 'Theft', respondent_name: 'Leo Garcia', created_at: 'March 1, 2024' },
  { id: 31, status: 'Pending', crime_type: 'Fraud', respondent_name: 'Julia Martinez', created_at: 'March 2, 2024' },
  { id: 32, status: 'Resolved', crime_type: 'Burglary', respondent_name: 'Dylan Turner', created_at: 'March 3, 2024' },
  { id: 33, status: 'Pending', crime_type: 'Assault', respondent_name: 'Aria White', created_at: 'March 4, 2024' },
  { id: 34, status: 'Under Investigation', crime_type: 'Drug Possession', respondent_name: 'Carter Brown', created_at: 'March 5, 2024' },
  { id: 35, status: 'Pending', crime_type: 'Public Disturbance', respondent_name: 'Amelia Taylor', created_at: 'March 6, 2024' },
  { id: 36, status: 'Resolved', crime_type: 'Embezzlement', respondent_name: 'Mason Anderson', created_at: 'March 7, 2024' },
  { id: 37, status: 'Pending', crime_type: 'Stalking', respondent_name: 'Hannah Wilson', created_at: 'March 8, 2024' },
  { id: 38, status: 'Under Investigation', crime_type: 'Human Trafficking', respondent_name: 'Isaac Davis', created_at: 'March 9, 2024' },
  { id: 39, status: 'Resolved', crime_type: 'Arson', respondent_name: 'Scarlett Martinez', created_at: 'March 10, 2024' },
  { id: 40, status: 'Pending', crime_type: 'Hate Crime', respondent_name: 'Elijah Anderson', created_at: 'March 11, 2024' },
  { id: 41, status: 'Under Investigation', crime_type: 'Robbery', respondent_name: 'Layla Foster', created_at: 'March 12, 2024' },
  { id: 42, status: 'Pending', crime_type: 'Money Laundering', respondent_name: 'Jackson Davis', created_at: 'March 13, 2024' },
  { id: 43, status: 'Resolved', crime_type: 'Cyberbullying', respondent_name: 'Penelope Turner', created_at: 'March 14, 2024' },
  { id: 44, status: 'Pending', crime_type: 'Car Theft', respondent_name: 'Mateo Garcia', created_at: 'March 15, 2024' },
  { id: 45, status: 'Under Investigation', crime_type: 'Vandalism', respondent_name: 'Mia Patel', created_at: 'March 16, 2024' },
  { id: 46, status: 'Pending', crime_type: 'Assault', respondent_name: 'Aiden Khan', created_at: 'March 17, 2024' },
  { id: 47, status: 'Resolved', crime_type: 'Cybercrime', respondent_name: 'Emma Miller', created_at: 'March 18, 2024' },
  { id: 48, status: 'Under Investigation', crime_type: 'Forgery', respondent_name: 'Noah White', created_at: 'March 19, 2024' },
  { id: 49, status: 'Pending', crime_type: 'Drug Trafficking', respondent_name: 'Grace Taylor', created_at: 'March 20, 2024' },
  { id: 50, status: 'Resolved', crime_type: 'Physical abuse', respondent_name: 'Liam Anderson', created_at: 'March 21, 2024' },
];

export { complaintsData };
